apiVersion: v1
kind: Pod
metadata:
  name: test-ns-webserver
  labels:
    app: myapp
spec:
  containers:
    - name: my-pod1
      image: nginx:1.16
      imagePullPolicy: Never
      resources:
        requests:
          memory: 1Mi
        limits:
          memory: 200Mi
