apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app: myapp1
spec:
  containers:
    - name: my-pod1
      image: nginx:1.16
      imagePullPolicy: Never
      # resources:
      #   requests:
      #     memory: 1Mi
      #   limits:
      #     memory: 200Mi
