apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-cluster-role-binding
subjects:
- kind: User
  name: rahul
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
