apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    appname: my-pod
  annotations:
    kubernetes.io/change-cause: "my first message"
spec:
  containers:
    - name: my-pod1
      image: nginx:1.16
      imagePullPolicy: Never
      resources:
        requests:
          memory: 1Mi
        limits:
          memory: 200Mi
