apiVersion: v1
kind: ServiceAccount
metadata:
  name: rahul
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rahul-pod-viewer
subjects:
- kind: ServiceAccount
  name: rahul
  namespace: default
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
